Place story
dizzyapp/iOS-Project pull request #10
Opened 2019-05-05 20:36 UTC by talbenasuli

Added PlaceStory viewController WIP.

2019-05-22 20:12 UTC, menesh2 requested changes
good job man :)

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentTextFieldView.swift
> +        button.setTitle("Send", for: .normal)
please use `"send.localized()"`

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentTextFieldView.swift
> +        }
for all above static numbers please use `Metrics` and if it does not exists on Metrics please add it as a static member

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentsManger.swift
> +protocol CommentsMangerDelegate: class {
missing "a" in the word manager

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentsManger.swift
> +final class CommentsManger: NSObject {
same as above

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentsManger.swift
> +    private let parentView: UIView
i dont think its a good practice to hold the parent view, why didnt you create an independent view `CommentsView: UIView` that interacts with its delegate instead of holding the parent view?

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentsManger.swift
> +        parentView.endEditing(true)
should be called with delegate pattern regard my comment above

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentsManger.swift
> +        delegate?.commecntView(isHidden: commentsView.isHidden)
commecntView? there is extra 'c'

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/Comments/CommentsView.swift
> +protocol CommentsViewDelegate: class {
i think comments manager should be combine with this class and do everything here

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/PlaceStoryVC.swift
> +            make.width.equalTo(150)
please make "150" class variable

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/PlaceStoryVC.swift
> +            make.width.equalTo(150)
same as above, you can use the same variable from above comment

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/Screens/PlaceStory/PlaceStoryVM.swift
> +    var showImage: (String) -> Void { get set }
why wont you make this observable called imageUrl? the name showImage fells like boolean and its not

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/UI Components/TextFieldBuilder.swift
> +    }
this is not enough because the text you write gets cut because the rounded corners

2019-05-22 20:12 UTC, menesh2 commented on Dizzy/UI Components/LoadinContainer.swift
> +//
very nice!!!!!!

2019-05-26 18:59 UTC, talbenasuli commented on Dizzy/Screens/PlaceStory/Comments/CommentsManger.swift
> +    private let parentView: UIView
The presentation of the comments view has some logic, that's the reason I created the manager, the manager includes the presentation logic, that's why it must have the parentView.
I have 2 viewControllers that need to present the comments view
1. The view controller that shows images
2. the view controller that show the videos
for that reason I created a manager that know how and when to display the view.
But I notice that the parent view must be weak, I will fix that.

2019-05-26 19:46 UTC, talbenasuli commented on Dizzy/UI Components/LoadinContainer.swift
> +//
TY

2019-06-03 18:53 UTC, merged