Feature/place profile
dizzyapp/iOS-Project pull request #14
Opened 2019-06-02 19:39 UTC by talbenasuli

Have Fun...

2019-06-03 20:04 UTC, menesh2 requested changes

2019-06-03 20:04 UTC, menesh2 commented on Dizzy/Extensions/DateUtils.swift
> +enum DayType: String {
please check if you need this class,
you can make `PlaceSchedule` enum as well and enum can be codable, hence you dont need `DayType`

2019-06-03 20:04 UTC, menesh2 commented on Dizzy/Screens/PlaceProfile/PlaceProfileVC.swift
> +        if let url = URL(string: viewModel.placeInfo.profileVideoURL ?? "") {
please remove lines 24- 27 to separate function called `loadVideo()` or something like that

2019-06-03 20:04 UTC, menesh2 commented on Dizzy/Screens/PlaceProfile/PlaceProfileVC.swift
> +        videoGravity = .resizeAspectFill
please remove lines 28- 31 to separate function called `setupView`

2019-06-03 20:04 UTC, menesh2 commented on Dizzy/Screens/PlaceProfile/PlaceProfileVM.swift
> +    var googlePlaceData = Observable<GooglePlaceData?>(nil)
remove this

2019-06-03 20:04 UTC, menesh2 commented on Dizzy/Screens/PlaceProfile/PlaceProfileView.swift
> +    func configure(with googlePlace: GooglePlaceData) {
delete

2019-06-03 20:04 UTC, menesh2 commented on Dizzy/Web Service/WebServiceDispatcher.swift
> +        self.webServices = [FirebaseWebService(), GooglePlaceService()]
remove googleplaceService

2019-06-10 20:56 UTC, talbenasuli commented on Dizzy/Extensions/DateUtils.swift
> +enum DayType: String {
we talk about it.

2019-06-10 20:58 UTC, talbenasuli commented on Dizzy/Screens/PlaceProfile/PlaceProfileVC.swift
> +        if let url = URL(string: viewModel.placeInfo.profileVideoURL ?? "") {
Done

2019-06-10 21:00 UTC, talbenasuli commented on Dizzy/Screens/PlaceProfile/PlaceProfileVC.swift
> +        videoGravity = .resizeAspectFill
I prefer not doing that because every place in the application we call those functions on init function.

2019-06-10 21:05 UTC, talbenasuli commented on Dizzy/Web Service/WebServiceDispatcher.swift
> +        self.webServices = [FirebaseWebService(), GooglePlaceService()]
Done.

2019-06-11 18:24 UTC, merged