Feature(GeneralChangesUI): added assets  & UI edits in multiple screens
dizzyapp/iOS-Project pull request #49
Opened 2019-11-18 08:38 UTC by Benlevy1025

Added new App icons
Updated Assets
Changed text, colors, alpha, fonts, corner radius and sized on multiple screens.
...To be continued
made "place info" animation appear faster
**Changed default current location to "Eastern Tel Aviv" instead of "Australia"**

2019-11-18 18:42 UTC, menesh2 requested changes

2019-11-18 18:42 UTC, menesh2 commented on Dizzy/Screens/Search Place/PlaceSearchVC.swift
> +            make.trailing.equalToSuperview().inset(Metrics.doublePadding)
please use offset and add -

2019-11-18 18:42 UTC, menesh2 commented on Dizzy/UI Components/PlaceInfoView.swift
> +        reservationButton.titleLabel?.font =  UIFont(name: "Avenir-Heavy" , size: 12)
please use `Fonts.h11(.bold)`

2019-11-18 20:33 UTC, Benlevy1025 commented on Dizzy/Screens/Search Place/PlaceSearchVC.swift
> +            make.trailing.equalToSuperview().inset(Metrics.doublePadding)
done

2019-11-18 20:37 UTC, Benlevy1025 commented on Dizzy/UI Components/PlaceInfoView.swift
> +        reservationButton.titleLabel?.font =  UIFont(name: "Avenir-Heavy" , size: 12)
dizzy done

2019-11-19 07:50 UTC, menesh2 approved these changes

2019-11-19 07:50 UTC, merged